#!/usr/bin/perl

use strict;
use warnings;
use POSIX qw(ceil);
use Time::HiRes qw/time sleep/;
use Getopt::Long;

my $interval = 4;
my $ncams = 3;
my $device = "/dev/video0";

GetOptions(
	'interval=s' => \$interval,
	'device=s' => \$device,
	'ncams=s' => \$ncams
    ) or exit 1;

print "interval = $interval\n";
print "ncams = $ncams\n";
print "device = $device\n";


sub launch {
    my $pid = fork();
    if ($pid) {
        waitpid($pid, 0);
        return;
    } 
    exec @_;
    die "Couldn't exec";
}

$SIG{CHLD} = 'IGNORE';

while (1) {
    my $now = time();

    my $ncam = $now / $interval % $ncams;
    print "now = " . $now . ", ncam = $ncam\n";
    launch("v4l2-ctl", "-d", $device, "-i", $ncam);
    $now = time();

    my $nextrun = ceil($now / $interval) * $interval;
    my $delay = $nextrun - $now;
    print "now = $now, nextrun = $nextrun, delay = $delay\n";
    print "\n";
    sleep $delay;
}

